/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/woman_statue.glb --transform --simplify 
Files: public/models/woman_statue.glb [1.99MB] > /Users/lucatam/Documents/Sapienza/web/museion/frontend/woman_statue-transformed.glb [194.55KB] (90%)
Author: schmoldt.art (https://sketchfab.com/schmoldt.art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/woman-statue-351df1c34c724196a75f6dabb6ecbd74
Title: Woman Statue
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CenterModel(props) {
  const { nodes, materials } = useGLTF('/models/woman_statue-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.WomanRockLow_WorldGridMaterial_0.geometry} 
        material={materials.WorldGridMaterial} 
        position={[0, 0, -70]} 
        rotation={[Math.PI / 2, Math.PI, Math.PI]} 
        scale={[0.3, 0.3, 0.3]}
        castShadow
        receiveShadow/>
    </group>
  )
}

useGLTF.preload('/models/woman_statue-transformed.glb')
